name: flutter_bloc_store
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
    
  # BLoc
  equatable: ^2.0.3
  bloc_test: ^9.0.2
  flutter_bloc: ^8.0.1

  # Authentication Repo
  firebase_auth: ^3.3.5
  firebase_core: ^1.11.0
  google_sign_in: ^5.2.3

  # Superheroes Repo
  http: ^0.13.4

  # others
  formz: ^0.4.1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
